[tools]
# utilities
# cat but with color support, also needed for fzf.
"bat" = "latest"
"cmake" = "latest"
"jq" = "latest"
"opencode" = "latest"
# Quick search, also needed for fzf.
"rg" = "latest"

# bash
"npm:bash-language-server" = "latest"

# cmake
"cargo:neocmakelsp" = "latest"

# cpp
"pipx:clang-format" = "22"
# Here is the version of the wheel package with cppcheck,
# which may not match the version of cppcheck itself.
"pipx:cppcheck" = "1"

# js
"node" = "lts"
# also needed for markdown
"npm:prettier" = "latest"

# python
"uv" = "latest"
"pipx:pyright" = "latest"
"pipx:pylint" = "4"
"pipx:ruff" = "0.15"
