" Generated by vim-plug
" четверг, 21 августа 2025 г. 16:42:51
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['YouCompleteMe'].commit = '131b1827354871a4e984c1660b6af0fefca755c3'
silent! let g:plugs['ale'].commit = '9e49019a2683bff012d53f28546ff968075ea3b9'
silent! let g:plugs['catppuccin'].commit = 'fa42eb5e26819ef58884257d5ae95dd0552b9a66'
silent! let g:plugs['fugitive-gitlab.vim'].commit = '3584cf7e607ba7822f991d407a8d780e05aae287'
silent! let g:plugs['fzf'].commit = '4811e52af3ed7f89e82baa908f9a8a25fb593361'
silent! let g:plugs['fzf.vim'].commit = '3725f364ccd25b85a91970720ba9bc2931861910'
silent! let g:plugs['glyph-palette.vim'].commit = '675f0ad64e2c4b823bffc1907d469deefaf6e3bd'
silent! let g:plugs['gruvbox'].commit = '697c00291db857ca0af00ec154e5bd514a79191f'
silent! let g:plugs['lsp-examples'].commit = '46db2070275e00e16359ce6a02e7b8ba76691aa2'
silent! let g:plugs['nerdtree'].commit = '9b465acb2745beb988eff3c1e4aa75f349738230'
silent! let g:plugs['pear-tree'].commit = '2d2fb6d5893d26be2ef280852f80494ff166529a'
silent! let g:plugs['supertab'].commit = 'f0093ae12a9115498f887199809a6114659fc858'
silent! let g:plugs['vim-airline'].commit = '41c5f54507fd865c8c00fe1f4bb390a59b6894ef'
silent! let g:plugs['vim-airline-themes'].commit = '0e976956eb674db8a6f72fae4dda6d1277433660'
silent! let g:plugs['vim-code-dark'].commit = '4624dc223bf574aa9a731c2383c579847303c380'
silent! let g:plugs['vim-code-runner'].commit = 'af6242b0a1b8651f5add636139ba87aced8a881c'
silent! let g:plugs['vim-devicons'].commit = '71f239af28b7214eebb60d4ea5bd040291fb7e33'
silent! let g:plugs['vim-floaterm'].commit = 'b18b41d15d2492f74f01ecac12f786b81f38262e'
silent! let g:plugs['vim-fugitive'].commit = '593f831d6f6d779cbabb70a4d1e6b1b1936a88af'
silent! let g:plugs['vim-polyglot'].commit = 'f5393cfee07aeb666f4d75f9b3a83163862fb094'
silent! let g:plugs['vim-rhubarb'].commit = '386daa2e9d98e23e27ad089afcbe5c5a903e488d'
silent! let g:plugs['vim-sublime-monokai'].commit = 'feb7935e92981590794d906a94355a767b6d1380'
silent! let g:plugs['vim-visual-multi'].commit = 'a6975e7c1ee157615bbc80fc25e4392f71c344d4'
silent! let g:plugs['vim-wintabs'].commit = '6d18d62ae0f293a108afee8c514706027faefcf3'
silent! let g:plugs['vim-wintabs-powerline'].commit = 'c6713349aa965ed32c0f6927e7121c8e04b27163'
silent! let g:plugs['vimspector'].commit = '5e24df822e278ee79abfc8c7110089a5322d1a3c'

PlugUpdate!

