noremap E g_
noremap Q ^
noremap q ge

" russian
map А F
map В D
map Г U
map Ж :
map Й Q
map К R
map М V
map П G
map У E
map Ф A
map Х {
map Ц W
map Ч X
map Ш I
map Ъ }
map Ы S

map а f
map в d
map г u
map д l
map з p
map й q
map к r
map л k
map м v
map н y
map о j
map р h
map с c
map у e
map ф a
map ц w
map ч x
map ш i
map щ o
map ь m
map ы s
map пп gg

" tabs edit
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv

" debugger
noremap ;t editor.debug.action.toggleBreakpoint
noremap ;c workbench.debug.viewlet.action.removeAllBreakpoints
noremap ;r workbench.action.debug.start
" russian
noremap же editor.debug.action.toggleBreakpoint
noremap жс workbench.debug.viewlet.action.removeAllBreakpoints
noremap жк workbench.action.debug.start

" completion
nnoremap gd editor.action.revealDefinition
nnoremap пв editor.action.revealDefinition

" escape
noremap <C-c> <Esc>
inoremap <C-c> <Esc>
" russian
noremap <C-с> <Esc>
inoremap <C-с> <Esc>

" moving in buffer
noremap <C-h> <left>
noremap <C-j> <down>
noremap <C-k> <up>
noremap <C-l> <right>
inoremap <C-h> <left>
inoremap <C-j> <down>
inoremap <C-k> <up>
inoremap <C-l> <right>
" russian
noremap <C-р> <left>
noremap <C-о> <down>
noremap <C-л> <up>
noremap <C-д> <right>
inoremap <C-р> <left>
inoremap <C-о> <down>
inoremap <C-л> <up>
inoremap <C-д> <right>

" coderunner
noremap <C-r> code-runner.run
inoremap <C-r> code-runner.run
" russian
noremap <C-к> code-runner.run
inoremap <C-к> code-runner.run
