export XDG_CONFIG_HOME="${HOME}/.dotfiles"
# `uv tool install` packages
export PATH="${PATH}:${HOME}/.local/bin"
export PATH="${PATH}:${HOME}/.cargo/bin"
export FZF_DEFAULT_OPTS="--style full --layout reverse"
export GIT_EDITOR=vim
